# Generated by Django 5.0.2 on 2024-02-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_customuser_is_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff_member',
        ),
    ]
