version: '3'

services:
  web:
    build: .
    command:  python manage.py runserver 0.0.0.0:5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"