# Generated by Django 5.0.2 on 2024-02-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderinitialdata_template_selected_and_more'),
        ('resume_templates', '0002_rename_variation_templatevariation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateVariation',
            new_name='Variation',
        ),
    ]
