# Generated by Django 5.0.2 on 2024-03-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume_templates", "0005_remove_template_is_default_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                (
                    "variation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="resume_templates.variation",
                    ),
                ),
            ],
        ),
    ]
