# Generated by Django 5.0.2 on 2024-03-24 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume_templates", "0006_variationsetting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="variation_types",
        ),
    ]
