# Generated by Django 5.0.2 on 2024-02-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='activities',
            field=models.ManyToManyField(related_name='departments', to='dashboard.activitytag'),
        ),
    ]
