# Generated by Django 5.0.2 on 2024-02-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activitytag_department_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested')], max_length=15)),
                ('payment_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('template_selection', models.CharField(choices=[('none', 'None'), ('temp1', 'Template 1'), ('temp2', 'Template 2')], default='none', max_length=10)),
                ('old_cv', models.FileField(blank=True, null=True, upload_to='old_cvs/')),
                ('other_files', models.FileField(blank=True, null=True, upload_to='other_files/')),
                ('order_type', models.CharField(choices=[('new_order', 'New Order'), ('modification', 'Modification')], default='new_order', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_data', to='dashboard.contact')),
            ],
        ),
    ]
