# Generated by Django 5.0.2 on 2024-02-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_preliminarydata_old_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliminarydata',
            name='template_selection',
            field=models.CharField(choices=[('', 'None'), ('1', 'Template 1'), ('2', 'Template 2')], default='none', max_length=10),
        ),
    ]
