# Generated by Django 5.0.1 on 2024-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_customuser_status_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=15),
        ),
    ]
