# Generated by Django 5.0.1 on 2024-02-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_customuser_status_customuser_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='payment_status',
        ),
    ]
