# Generated by Django 5.0.2 on 2024-02-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_cv',
            field=models.FileField(blank=True, null=True, upload_to='order_old_cvs/'),
        ),
    ]
