# Generated by Django 5.0.2 on 2024-02-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_old_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='old_cv',
        ),
        migrations.CreateModel(
            name='OrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_files/')),
                ('file_type', models.CharField(choices=[('original_cv', ' Original CV'), ('original_pic', 'original_pic'), ('other', 'Other File')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
            ],
        ),
    ]
