# Generated by Django 5.0.2 on 2024-02-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_requirements_and_more'),
        ('resume_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinitialdata',
            name='template_selected',
        ),
        migrations.AddField(
            model_name='orderinitialdata',
            name='variation_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,to='resume_templates.Variation'),
        ),
    ]
