# Generated by Django 5.0.2 on 2024-02-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderinitialdata_template_selected_and_more'),
        ('resume_templates', '0003_rename_templatevariation_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinitialdata',
            name='variation_selected',
        ),
        migrations.AddField(
            model_name='orderinitialdata',
            name='template_variation_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_initial_data', to='resume_templates.variation'),
        ),
    ]
