# Generated by Django 5.0.2 on 2024-02-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderinitialdata_variation_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Stores the parsed CV data as JSON.')),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('no_cv', 'No CV'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parse', to='orders.order')),
            ],
        ),
    ]
