# Generated by Django 5.0.2 on 2024-02-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderparse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFinalizedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_data', models.JSONField(blank=True, default=dict, help_text='Stores the finalized CV data as JSON.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_data', to='orders.order')),
            ],
        ),
    ]
