# Generated by Django 5.0.2 on 2024-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_order_status_orderstatusupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderfinalizeddata",
            name="pdf_to_text_data",
            field=models.TextField(
                blank=True, help_text="Stores the PDF to text data."
            ),
        ),
        migrations.AddField(
            model_name="orderparse",
            name="pdf_to_text_data",
            field=models.TextField(
                blank=True, help_text="Stores the PDF to text data."
            ),
        ),
    ]
